// <auto-generated />
namespace WheresMyStuff.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitialItems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialItems));
        
        string IMigrationMetadata.Id
        {
            get { return "201601200319261_InitialItems"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
